#!/usr/bin/env bash
# Bootstrap a project-local Claude Code OAuth token without ever touching the
# host's `~/.claude/` credentials.
#
# Flow on first run (CLAUDE_CODE_OAUTH_TOKEN absent or empty in .env):
#   1. Spin up a one-shot, interactive Docker container with the Claude
#      Code CLI bundled (the same `claude` binary the workers use).
#   2. Run `claude setup-token` inside it. Claude prints an OAuth URL; you
#      open it in YOUR browser (host-side), authenticate, paste the
#      verification code back into the terminal. Claude prints a long-lived
#      token (~ 1 year).
#   3. Capture the token from the container's stdout.
#   4. Append `CLAUDE_CODE_OAUTH_TOKEN=<token>` to `.env`.
#   5. Done. The token is then injected into all worker containers via the
#      `worker_env` anchor in docker-compose.yml.
#
# Subsequent runs: no-op (the token is already in .env).
#
# Recovery from expiry / wanting a fresh token:
#   sed -i '' '/^CLAUDE_CODE_OAUTH_TOKEN=/d' .env
#   bun compose:dev
#
# This script never reads from ${HOME}/.claude/. Your host's Claude Code
# session is independent and never affected.

set -euo pipefail

ENV_FILE="$(pwd)/.env"
TOKEN_KEY="CLAUDE_CODE_OAUTH_TOKEN"

# Image whose entrypoint can run `claude setup-token`. We reuse the project's
# worker image since it already has the bundled Linux binary baked in.
IMAGE_TAG="trading-flow-claude-bootstrap:local"
DOCKERFILE="docker/Dockerfile.worker"

# Fast path: token already populated.
if [[ -f "$ENV_FILE" ]] && grep -qE "^${TOKEN_KEY}=.+" "$ENV_FILE"; then
  echo "✓ ${TOKEN_KEY} already set in .env"
  exit 0
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "✗ .env not found at $ENV_FILE — copy .env.example first." >&2
  exit 1
fi

# Build the worker image once (cheap if already cached).
echo "Building image for claude setup-token..."
docker build -q -t "$IMAGE_TAG" -f "$DOCKERFILE" . > /dev/null

cat <<'BANNER'

──────────────────────────────────────────────────────────────────────
  Claude Code OAuth — interactive setup
──────────────────────────────────────────────────────────────────────
  Claude will print an OAuth URL. Open it in YOUR browser, authorize,
  then paste the verification code BACK into this terminal when asked.

  This token is project-local — your host's ~/.claude/ is untouched.
──────────────────────────────────────────────────────────────────────

BANNER

# Run setup-token interactively. Stdout is a mix of prompts and the final
# token line; we tee to both the user's terminal AND a log file so we can
# extract the token deterministically afterward.
LOG_FILE="$(mktemp -t claude-setup-token.XXXXXX)"
trap 'rm -f "$LOG_FILE"' EXIT

# --network=host lets the device-flow callback reach localhost if claude
# uses a local listener; harmless on Linux/Mac if it doesn't.
docker run --rm -it \
  --network=host \
  --entrypoint /app/node_modules/@anthropic-ai/claude-agent-sdk-linux-arm64/claude \
  "$IMAGE_TAG" \
  setup-token 2>&1 | tee "$LOG_FILE"

# Extract the token. Claude Code prints lines like:
#   Long-lived token: sk-ant-oat01-xxxxxxxx
# but the exact prefix may vary. We accept anything matching `sk-ant-oat...`.
TOKEN=$(grep -oE 'sk-ant-oat[A-Za-z0-9_-]{20,}' "$LOG_FILE" | tail -1 || true)

if [[ -z "$TOKEN" ]]; then
  echo ""
  echo "✗ Could not capture an OAuth token from the setup-token output." >&2
  echo "  If the token was printed, re-run and copy it manually:" >&2
  echo "    echo 'CLAUDE_CODE_OAUTH_TOKEN=<paste-token-here>' >> .env" >&2
  exit 1
fi

# Append to .env (idempotent: the fast-path check above ensures we don't
# duplicate the line).
{
  echo ""
  echo "# === Claude Code OAuth (project-local, generated by"
  echo "#     scripts/dev/bootstrap-claude-token.sh — do not commit) ==="
  echo "${TOKEN_KEY}=${TOKEN}"
} >> "$ENV_FILE"

echo ""
echo "✓ ${TOKEN_KEY} appended to .env"
echo "  The token is propagated to workers via docker-compose.yml worker_env anchor."
