#!/usr/bin/env bash
# Bootstrap a project-local Claude Code OAuth token without ever touching the
# host's `~/.claude/` credentials.
#
# Flow on first run (CLAUDE_CODE_OAUTH_TOKEN absent or empty in .env):
#   1. Spin up a one-shot, interactive Docker container with the Claude
#      Code CLI bundled (the same `claude` binary the workers use).
#   2. Run `claude setup-token` inside it. Claude prints an OAuth URL; you
#      open it in YOUR browser (host-side), authenticate, paste the
#      verification code back into the terminal. Claude prints a long-lived
#      token (~ 1 year).
#   3. Capture the token from the container's stdout.
#   4. Append `CLAUDE_CODE_OAUTH_TOKEN=<token>` to `.env`.
#   5. Done. The token is then injected into all worker containers via the
#      `worker_env` anchor in docker-compose.yml.
#
# Subsequent runs: no-op (the token is already in .env).
#
# Recovery from expiry / wanting a fresh token:
#   sed -i '' '/^CLAUDE_CODE_OAUTH_TOKEN=/d' .env
#   bun compose:dev
#
# This script never reads from ${HOME}/.claude/. Your host's Claude Code
# session is independent and never affected.

set -euo pipefail

ENV_FILE="$(pwd)/.env"
TOKEN_KEY="CLAUDE_CODE_OAUTH_TOKEN"

# We reuse one of the project's already-built worker images (they all have
# the bundled `claude` Linux binary baked in). Falling back to a fresh build
# only if no image exists yet.
WORKER_IMAGE="trading-flow-analysis-worker:latest"
FALLBACK_BUILD_TAG="trading-flow-claude-bootstrap:local"
DOCKERFILE="docker/Dockerfile.worker"

# Fast path: token already populated.
if [[ -f "$ENV_FILE" ]] && grep -qE "^${TOKEN_KEY}=.+" "$ENV_FILE"; then
  echo "✓ ${TOKEN_KEY} already set in .env"
  exit 0
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "✗ .env not found at $ENV_FILE — copy .env.example first." >&2
  exit 1
fi

# Pick an image. Reuse the worker image if it exists (fast: 0s), else build
# the bootstrap image (slow: 1-2 min on first run, with progress visible).
if docker image inspect "$WORKER_IMAGE" >/dev/null 2>&1; then
  IMAGE_TAG="$WORKER_IMAGE"
  echo "✓ Reusing existing worker image: $IMAGE_TAG"
else
  IMAGE_TAG="$FALLBACK_BUILD_TAG"
  echo "Building bootstrap image (one-time, ~1-2 min)..."
  # No -q so the user sees build progress; goes to stderr by default.
  docker build -t "$IMAGE_TAG" -f "$DOCKERFILE" .
fi

cat <<'BANNER'

──────────────────────────────────────────────────────────────────────
  Claude Code OAuth — interactive setup
──────────────────────────────────────────────────────────────────────
  Claude will print an OAuth URL. Open it in YOUR browser, authorize,
  then paste the verification code BACK into this terminal when asked.

  This token is project-local — your host's ~/.claude/ is untouched.
──────────────────────────────────────────────────────────────────────

BANNER

# Run setup-token interactively. Claude prints an OAuth URL → user opens it
# in their browser → completes login → claude prints the long-lived token
# directly in the terminal.
#
# We do NOT try to auto-capture the token: BSD `script(1)` on macOS records
# ANSI escape codes + cursor manipulations in a way that makes regex extraction
# unreliable (tested: ends up gluing the token to the next sentence "Store
# this token securely." with no separator, producing 401-rejected corrupted
# tokens). A 3-second paste is bulletproof.
#
# --network=host lets the OAuth callback reach localhost if claude uses
# a local listener; harmless if it doesn't.
docker run --rm -it \
  --network=host \
  --entrypoint /app/node_modules/@anthropic-ai/claude-agent-sdk-linux-arm64/claude \
  "$IMAGE_TAG" \
  setup-token

cat <<'PROMPT'

──────────────────────────────────────────────────────────────────────
  Copy the token printed above (the line starting with `sk-ant-oat01-`)
  and paste it below. The script appends it to .env.

  Tip: triple-click the token line to select the whole token cleanly,
  then ⌘C / Ctrl+C to copy. Avoid selecting "Store" from the next line.
──────────────────────────────────────────────────────────────────────

PROMPT

read -r -p "Token: " TOKEN

# Strip whitespace defensively (paste sometimes includes trailing space).
TOKEN="${TOKEN#"${TOKEN%%[![:space:]]*}"}"
TOKEN="${TOKEN%"${TOKEN##*[![:space:]]}"}"

# Strict validation: tokens are typically ~108 chars; reject anything outside
# the plausible 90-130 range or with the wrong prefix.
if [[ ! "$TOKEN" =~ ^sk-ant-oat[0-9]+-[A-Za-z0-9_-]+$ ]] || \
   [[ ${#TOKEN} -lt 90 ]] || \
   [[ ${#TOKEN} -gt 130 ]]; then
  echo ""
  echo "✗ Token does not look valid:" >&2
  echo "    expected: sk-ant-oat... 90-130 chars, base64url chars only" >&2
  echo "    got:      ${#TOKEN} chars" >&2
  echo "  Re-run \`bun compose:dev\` and try again." >&2
  exit 1
fi

# Append to .env (idempotent: the fast-path check above ensures we don't
# duplicate the line).
{
  echo ""
  echo "# === Claude Code OAuth (project-local, generated by"
  echo "#     scripts/dev/bootstrap-claude-token.sh — do not commit) ==="
  echo "${TOKEN_KEY}=${TOKEN}"
} >> "$ENV_FILE"

echo ""
echo "✓ ${TOKEN_KEY} appended to .env"
echo "  The token is propagated to workers via docker-compose.yml worker_env anchor."
